#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Struct-Dumb
Version  : 0.09
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Struct-Dumb-0.09.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Struct-Dumb-0.09.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libstruct-dumb-perl/libstruct-dumb-perl_0.09-1.debian.tar.xz
Summary  : 'make simple lightweight record-like structures'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Struct-Dumb-license
Requires: perl-Struct-Dumb-man
Requires: perl(Test::Fatal)
Requires: perl(Try::Tiny)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)

%description
NAME
Struct::Dumb - make simple lightweight record-like structures
SYNOPSIS
use Struct::Dumb;

struct Point => [qw( x y )];

my $point = Point(10, 20);

printf "Point is at (%d, %d)\n", $point->x, $point->y;

$point->y = 30;
printf "Point is now at (%d, %d)\n", $point->x, $point->y;

%package license
Summary: license components for the perl-Struct-Dumb package.
Group: Default

%description license
license components for the perl-Struct-Dumb package.


%package man
Summary: man components for the perl-Struct-Dumb package.
Group: Default

%description man
man components for the perl-Struct-Dumb package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Struct-Dumb-0.09
mkdir -p %{_topdir}/BUILD/Struct-Dumb-0.09/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Struct-Dumb-0.09/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Struct-Dumb
cp LICENSE %{buildroot}/usr/share/doc/perl-Struct-Dumb/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Struct/Dumb.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Struct-Dumb/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Struct::Dumb.3
